import { Container } from "@mui/material";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Realtime chat app",
  description: "Generated by create next app",
};

function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Container
      sx={{ minHeight: "100vh" }}
      component={"section"}
      className="flex items-center justify-center"
    >
      {children}
    </Container>
  );
}

export default LoginLayout;
