export interface ISimpleConversation {
  id: number;
  title: string;
  lastMessage: string;
  avatar: string;
  type: number;
}

export const _conservations: ISimpleConversation[] = [
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
  {
    id: Math.floor(Math.random() * 100),
    title: "Duy Nguyễn " + Math.floor(Math.random() * 100),
    avatar: "https://api.dicebear.com/8.x/adventurer/svg?seed=Misty",
    lastMessage: "Last message",
    type: 0,
  },
];